### PR TITLE
Fixed import libmagic for windows

### PR DESCRIPTION
**Pull request by sal-git**
I don't program in python so I don't really know PEP8, so if it doesn't pass the tests - blah

### CODE REVIEW

**Comment by sal-git** [comment]
May you teach me how to circumvent that error? :/ 

lol

**Comment by sim0nx** [comment]
Hi

Thanks for the PR!
Though this is not a valid fix for Windows. Even if you import "libmagic" that just results in the eml_parser not using any mime-parsing code at all as the expected import is "magic".
That is also why the code quality check fails with the error "unused import" -> it is not used anywhere.

Though it works for you is just because you leave "magic" undefined with your if clause.

If you can live without having mime parsing support, it would be better to uninstall "file-magic".

Please note the required libmagic DLL is not the same as the file-magic python module.

**Comment by sal-git** [comment]
Ah, sorry for that. I understand now, thank you! 

And thank you for the library!

**Comment by sim0nx** [comment]
No problem! :-)

**Pull request closed without merging**
