### PR TITLE
Switch from re to re2

### PR DESCRIPTION
**Pull request by jamie-34254**
Switching to the re2 library fixes some hangs we were getting on malformed e-mails causing `for found_url in eml_parser.regex.url_regex_simple.findall(body)` to infinitely hang.

Certain inputs into this regex cause very bad backtracking which is able to lock up execution for hours on end.

A simple test case is: `http://asd.com/"""""""""""""""""""""""""""""""""""""""`

We also came up with a possible replacement regex but we're not sure if it will continue working as you were expecting:

```
r'''(?i)\b(?:https?|ftps?):(?:\/{1,3}|[a-z0-9%])(?:[^\s()<>{}\[\]]+?|\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\))+?(?:[\w\-._~%!$&'()*+,;=:\/?#\[\]@]+)'''
```

### CODE REVIEW

**Comment by sim0nx** [comment]
Thanks for your issue report / PR.

I don't think re2 is a good replacement. The repo hasn't seen any updates since 2016 (though the latest version is from 2019?).

A possible alternative could be regex (https://pypi.org/project/regex/) which is also mentioned in the python docs (https://docs.python.org/3/library/re.html).

That requires thorough testing though in order to make sure things do not break. I haven't tried it in a long time.

If you could give *regex* a try, I would be interested in your feedback :-)
At least with your test case it works fine.

**Comment by sim0nx** [comment]
I just realise from your changes that you are referring to pyre2 (https://pypi.org/project/pyre2/), not re2 (https://pypi.org/project/re2/).

**Comment by jamie-34254** [comment]
> I just realise from your changes that you are referring to pyre2 (https://pypi.org/project/pyre2/), not re2 (https://pypi.org/project/re2/).

sorry, I should have been more specific. I was referring to https://github.com/google/re2 when I said re2, not the library which I used: https://pypi.org/project/pyre2/

> That requires thorough testing though in order to make sure things do not break. I haven't tried it in a long time.
Understood, the test suite did run when I tested it but I don't know how comprehensive you would consider it

**Comment by sim0nx** [comment]
> > I just realise from your changes that you are referring to pyre2 (https://pypi.org/project/pyre2/), not re2 (https://pypi.org/project/re2/).
> 
> sorry, I should have been more specific. I was referring to https://github.com/google/re2 when I said re2, not the library which I used: https://pypi.org/project/pyre2/

np, I would prefer pyre2 over google-re2 though as they provide way more wheel packages which makes it easier to install it.

> > That requires thorough testing though in order to make sure things do not break. I haven't tried it in a long time.
> 
> Understood, the test suite did run when I tested it but I don't know how comprehensive you would consider it

That's a start but not enough as it does not contain a lot of related sample data. It should be run on larger quantities of EML files which contain testable data and be compared to using *re*.
I will do the tests on my side but that will take some time.

Until then, you can easily switch the regex engine with the latest version v1.15.0. See the changelog for details.

I am curious about your results.

Let's continue the discussion in #63 if you don't mind. I am closing this PR.

**Pull request closed without merging**
